/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.1
</auto-generated>
------------------------------------------------------------------------------ */

using System.Collections.Generic;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Libraries.Model;
using Telerik.Sitefinity.Model;
using System.Linq;
using Telerik.Sitefinity.RelatedData;

namespace RotatingCarousel.Mvc.Models
{
    public class RotatingImageCarouselModel
    {
        public string AlbumName { get; set; }

        public List<RotatingSlide> RotatingSlides { get; set; }

        public class RotatingSlide
        {
            public string Title { get; set; }
            public string Description { get; set; }
            public string ImageUrl { get; set; }
            public string ImageAlt { get; set; }    
        }

        public RotatingImageCarouselModel(List<Image> items)
        {
            this.RotatingSlides = SetRotatingSlides(items);
        }

        public List<RotatingSlide> SetRotatingSlides(List<Image> items)
        {
            List<RotatingSlide> rotatingSlides = new List<RotatingSlide>();
            foreach (var item in items)
            {
                RotatingSlide rotatingSlide = new RotatingSlide();
                rotatingSlide.Title = item.Title;
                rotatingSlide.Description = item.Description;
                rotatingSlide.ImageUrl = item.MediaUrl;
                rotatingSlide.ImageAlt = item.AlternativeText;
                rotatingSlides.Add(rotatingSlide);
            }
            return rotatingSlides;
        }
    }
}